In [40]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [50]:
data=pd.read_csv('Churn_Modelling.csv')
X=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values
X[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [42]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])


In [49]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('encode',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))
X[0]

array([1.0, 0.0, 1.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [44]:
from sklearn.model_selection import train_test_split
Xtr,Xte,Ytr,Yte=train_test_split(X,y,random_state=0)


In [45]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
Xtr=sc.fit_transform(Xtr)
Xte=sc.fit_transform(Xte)


In [59]:
from tensorflow.keras.models import Sequential
ann=Sequential()


In [60]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [61]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [62]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [63]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy']) #binary_crossentropy because the output is 0, 1 else activation=soft_max, category_cossentropy

In [64]:
ann.fit(Xtr,Ytr,batch_size=32,epochs=100)

Epoch 1/100
235/235 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7505
Epoch 2/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4585 - accuracy: 0.8056
Epoch 3/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4404 - accuracy: 0.8087
Epoch 4/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4326 - accuracy: 0.8101
Epoch 5/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4276 - accuracy: 0.8141
Epoch 6/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4236 - accuracy: 0.8165
Epoch 7/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4204 - accuracy: 0.8183
Epoch 8/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4173 - accuracy: 0.8189
Epoch 9/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4147 - accuracy: 0.8209
Epoch 10/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4132 - accura

In [65]:
ypred=ann.predict(Xte)
ypred=ypred>0.5

79/79 [==============================] - 0s 2ms/step


In [68]:
from sklearn.metrics import accuracy_score
Yte=Yte>0.5
ypred.flatten()

print("accuracy score = ",accuracy_score(Yte,ypred))

accuracy score =  0.8636


In [69]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Yte,ypred)
print(cm)

[[1917   74]
 [ 267  242]]
